services:
  nginx:
    build: ./client
    ports:
      - "9080:8080"
    volumes:
      - ./client/src:/var/www/public
  
  app:
    build: ./server
    volumes:
      - ./server:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    deploy:
      replicas: 1
    ports:
      - "9229:9229"
    command: node --run debug

  admin:
    image: mongo-express:1.0.2-20
    ports:
      - "9081:8081"
    depends_on:
      - mongo

volumes:
  node_modules: