version: '3.8'
services:
  nginx:
    image: ghcr.io/sfidanza/chat-frontend
    depends_on:
      - app
    
  app:
    image: ghcr.io/sfidanza/chat-backend
    environment:
      - NODE_PORT=9090
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
    expose:
      - 9090
    depends_on:
      - mongo
      - redis
    deploy:
      replicas: 3

  redis:
    image: redis:alpine

  mongo:
    image: mongo:4-focal  # MongoDB 5.0+ requires a CPU with AVX support. Does not run in production!
    volumes:
      - mongodb:/data/db
    expose:
      - 27017
    
volumes:
  mongodb: