version: '3.8'
services:
  nginx:
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.chat.rule=Host(`$HOST`)
        - traefik.http.services.chat.loadbalancer.server.port=80
        # Activate https
        - traefik.http.routers.chat.tls=true
        - traefik.http.routers.chat.tls.certresolver=myresolver
        - traefik.http.routers.chat.middlewares=security@file
    networks:
      - gateway
      - default

networks:
  gateway:
    external: true
    name: gateway